# script to build Jamoma on Travis-ci.org
# see : https://travis-ci.org/jamoma/jamoma2/

language: c++
compiler:
 # - gcc
  - clang
sudo: false

os: osx

osx_image: xcode6.4

#addons:
#  apt:
#    sources:
#    - llvm-toolchain-precise-3.6
#    - ubuntu-toolchain-r-test
#    packages:
#    - clang-3.6
 #   - gcc-4.9
#    - g++-4.9

before_install:
  # Prepare compiler
#  - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.6" CC="clang-3.6"; fi
#  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="clang-4.9"; fi


script:
- "make test"
