# script to build Jamoma on Travis-ci.org
# see : https://travis-ci.org/jamoma/jamoma2/

language: c++
compiler: clang
sudo: false


addons:
  apt:
    sources:
    - llvm-toolchain-precise-3.6
    - ubuntu-toolchain-r-test
    packages:
    - clang-3.6


before_install:
  # Prepare compiler
  - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.6" CC="clang-3.6"; fi


script:
- "make test"
